### ISSUE TITLE
Trouble including assets in addon (works in app)

### ISSUE THREAD

**Issue by dhdemerson** [dfreeman/ember-cli-node-assets#15]
Hello! I'm having trouble including assets in an addon I'm working on. The same configuration works when I tested it in an app. Here's the relevant [index.js](https://github.com/dhdemerson/ember-leaflet-iiif-tile-layer/blob/leaflet-iiif-node-assets/index.js)
```
module.exports = {
  name: 'ember-leaflet-iiif-tile-layer',
  options: {
    nodeAssets: {
      'leaflet-iiif': {
        vendor: {
          include: ['leaflet-iiif.js']
        }
      }
    }
  },
  included(app) {
    this._super.included.apply(this, arguments);

    app.import('vendor/leaflet-iiif/leaflet-iiif.js');
  }
};
```
This fails to build with `Error: ENOENT: no such file or directory, open '.../ember-leaflet-iiif-tile-layer/tmp/source_map_concat-input_base_path-g0baEhnw.tmp/vendor/leaflet-iiif/leaflet-iiif.js'`

If I use the import shorthand it will build successfully, but it doesn't seem like the script is ever actually included.

For reference this is the working `ember-cli-build.js` in a test app
```
module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    nodeAssets: {
      'leaflet-iiif': {
        vendor: {
          include: ['leaflet-iiif.js']
        }
      }
    }
  });

  app.import('vendor/leaflet-iiif/leaflet-iiif.js');

  return app.toTree();
};
```

**Comment by dfreeman** [comment]
Hi @dhdemerson — for addons, ember-cli-node-assets needs to be under `dependencies` rather than `devDependencies`. Otherwise Ember CLI won't consider it to be a dependency of the addon itself, only the dummy app.

This seems to be a pretty common point of confusion around addons that depend on addons in general, but just the other day someone submitted [a PR](https://github.com/dfreeman/ember-cli-node-assets/pull/13/files) to call that out explicitly in the README.

Hopefully that helps, and sorry for the confusion 🙂

**Comment by dhdemerson** [comment]
Moving ember-cli-node-assets to `dependencies` from `devDependencies` worked. Thanks for taking the time to explain. I imagine this addon will likely be used by a lot of first time addon developers like me so adding the note to the docs I'm sure will be very helpful :) 

Thanks again!
