### ISSUE TITLE
Import 3rd-party libraries directly from nested addon

### ISSUE THREAD

**Issue by nightire** [dfreeman/ember-cli-node-assets#7]
I'm trying to find the best practices to manage all types of dependencies management, with ember-cli-node-assets of course, currently I'm happy with:

1. [x] use it with stand-alone ember application
2. [x] use it with addon as directly dependency to an ember application w/o npm/bower install in it
3. [ ] same as no.2 but use it in a nested addon

Explicitly describing list 3:

I have an addon, let's call it **addon-A**, it wraps an 3rd-party library by using ember-cli-node-assets. in addition I expose both 3rd-party & ember-cli-node-assets as `dependencies` in _package.json_, it works.

Then I create another addon (let's call it **addon-B**) and `ember install addon-A`, still works as I expected.

Until I `ember install addon-B` in an ember application, now **addon-A** starts to import 3rd-party library from application's `node_modules` directory, it fails apparently.

I know why it is failed, and sure I know how to fix it by explicitly `npm install a-library` or use **addon-B**'s blueprint to automatically install a-library, but I'm expecting not to do this.

So if **addon-B** doesn't have to "tell" **addon-A** where to find its import path, how do I do to make application works just like **addon-B** did? Does ember-cli-node-assets support this out of box?

**Comment by dfreeman** [comment]
Hi @nightire, sorry for the long turnaround on this! Up to now, ember-cli-node-assets was specifically designed not to operate in a nested scenario like this. Suppose I introduce a third addon, `addon-C`, that also depends on `addon-A`. My dependency tree might now look something like:

```
my-app
├── addon-B@1.0
│   └── addon-A@1.0
│       └── 3rd-party-package@1.0
└── addon-C@1.0
    └── addon-A@1.0
        └── 3rd-party-package@1.0
```

If both copies of `addon-A` import `3rd-party-package`, you end up with two copies of the final library in the build. Worse, `addon-B` and `addon-C` could depend on _different versions_ of `addon-A` and `3rd-party-package`. To avoid this situation, ember-cli-node-assets has always recommended addons like `addon-B` to either list `addon-A` as a `peerDependency` or to include a blueprint to automatically install it in the parent app.

However, the landscape has changed some since this was originally published. Ember CLI 2.12 beta automatically deduplicates files that are imported more than once, and newer versions of npm (and Yarn) will avoid having multiple versions of a package if possible, lowering the changes of having different minor versions of a package around.

In light of that, I've just published `ember-cli-node-assets@0.2.0-beta.1`, which no longer has the limitation you mentioned. It likely won't leave beta status until Ember CLI 2.12 is officially released, but it's otherwise stable currently (just know that you could end up with multiple copies of an imported file when using the current CLI release).

**Comment by Panman8201** [comment]
If I could piggy-back on this issue/question, is it possible to import assets from the parent/app's `node_modules`? So let's say the addon `this.addPackageToProject();` in its' blueprint, can the addon then import assets from the projects dep?

In addition, is it possible to check to see if the parent/app has a dep for the specific package? (This question might be out-of-scope here...)

**Comment by dfreeman** [comment]
>  is it possible to import assets from the parent/app's node_modules? So let's say the addon this.addPackageToProject(); in its' blueprint, can the addon then import assets from the projects dep?

It is! That's a key piece of now Node.js dependency resolution works 🙂 . If I have a dependency tree like this:

```
my-app
├── fancy-lib@^1.0.0
│   └── some-base-lib@^1.2.0
└── some-base-lib@^1.1.3
```

Since `my-app` and `fancy-lib`'s dependencies on `some-base-lib` can both be satisfied by the same version, package managers are free to deduplicate and make the actual installation look like:

```
my-app
└── node_modules
    ├── fancy-lib (v1.1.0)
    └── some-base-lib (v1.3.1)
```

Because package managers are allowed to do that, Node's dependency resolution operates as a series of fallbacks. When `fancy-lib` goes to require a module from `some-base-lib`, if it's not found in `fancy-lib`'s dedicated `node_modules` directory, it'll look in its parent's `node_modules`, and so on up to the root package.

So in theory, at least, any package that the root has access to will also be available to all its dependencies. That said, if your own addon doesn't declare a dependency on a given package that it wants to import assets from, you can end up in a weird place if the user later goes "what's this doing in my dependencies?" and removes that package.

> In addition, is it possible to check to see if the parent/app has a dep for the specific package? (This question might be out-of-scope here...)

Ember CLI exposes the contents of various `package.json` files in different places, but I'm not sure how public that is and whether you'd be able to get at exactly what you want from there. I'd ask with more specific details of what you want to do in `#-ember-cli` in Slack.

**Comment by dfreeman** [comment]
@nightire I'm going to go ahead and close this now that v0.2.0 is stable, but as always feel free to reopen this or create a new issue if you have further questions.
